AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole

  ScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger Lambda every 5 minutes"
      ScheduleExpression: "rate(5 minutes)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt Function.Arn
          Id: "FunctionTarget"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Function
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduleRule.Arn

Outputs:
  Function:
    Description: "Lambda Function ARN"
    Value: !GetAtt Function.Arn 