AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  CodeBucket:
    Type: String
    Description: S3 bucket containing the Lambda function code
  CodeKey:
    Type: String
    Description: S3 key of the Lambda function code
  PhoneNumber:
    Type: String
    Description: Phone number to send SMS to (in E.164 format, e.g., +1234567890)

Resources:
  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SNSPublishPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref SNSTopic

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: HelloWorldSMS

  SNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sms
      TopicArn: !Ref SNSTopic
      Endpoint: !Ref PhoneNumber

  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
      Handler: app.lambda_handler
      Role: !GetAtt FunctionRole.Arn
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SNSTopic

  ScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger Lambda every 5 minutes"
      ScheduleExpression: "rate(5 minutes)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt Function.Arn
          Id: "FunctionTarget"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Function
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduleRule.Arn

Outputs:
  Function:
    Description: "Lambda Function ARN"
    Value: !GetAtt Function.Arn
  SNSTopic:
    Description: "SNS Topic ARN"
    Value: !Ref SNSTopic 